check-available-space: make whole script sudoable

diff --git a/check-available-space b/check-available-space
--- a/check-available-space
+++ b/check-available-space
@@ -6,11 +6,17 @@ log() {
   echo "[$logPrefix] $*"
 }
 
-log "WARNING: sudo is required to check size of postgres docker volume."
+if ! sudo -n true 2>/dev/null; then
+  log
+  log "WARNING: sudo may be required to:"
+  log
+  log "  1. check size of postgres docker volume."
+  log "  2. check size of postgres docker volume."
+  log
+fi
 
-# Check available space in the docker root dir.  This is less risky than with /volumes appended
-# as on some systems the docker root dir may not be executable by the current user.
-free="$(df --output=avail "$(docker info --format '{{print .DockerRootDir}}')" | tail -n+2)"
+dockerRootDir="$(docker info --format '{{print .DockerRootDir}}')"
+free="$(df --output=avail "$dockerRootDir/volumes" | tail -n+2)"
 
 containerName="central_postgres_1"
 volume="$(docker inspect --format='{{(index .Mounts 0).Name}}' "$containerName")"
@@ -23,7 +29,7 @@ if [[ "$volume" = "" ]]; then
   exit 1
 fi
 mountpoint="$(docker volume inspect --format='{{.Mountpoint}}' "$volume")"
-used="$(sudo du -s "$mountpoint" | cut -f1)"
+used="$(du -s "$mountpoint" | cut -f1)"
 
 log
 log "    Free space: $(numfmt --to=si "$((free*1000))")B"
